<?php

$data = [
    [
        "first-name" => "Philip",
        "last-name" => "Fry",
        "image" => "https://upload.wikimedia.org/wikipedia/en/2/28/Philip_Fry.png",
        "age" => "25",
        "gender" => "Male",
        "species" => "Human",
        "homePlanet" => "Earth",
        "occupation" => "Intergalactic Delivery Boy",
        "sayings" => [
            "Shut up and take my money!",
            "I'm walking on sunshine, woah oh oooh",
            "This is how we do it. Pick your nose and chew it",
            "wow! I never would have thought of that.",
            "Bigfoot! He's real! I knew it! The Loch Ness Monster's book was right!",
            "I didn't ask for a completely reasonable excuse! I asked you to get busy!",
            "It's like a party in my mouth and everybody's throwing up!",
            "My God, it's full of ads!",
            "There's so many killbots behind us, I can't count them all. Three, I think.",
            "They're like sex, except I'm having them!",
            "We're in the middle of nowhere, which is the safest part of nowhere.",
            "When will young people learn that playing 'Dungeons and Dragons' doesn't make you cool!",
            "Why am I sticky and naked? Did I miss something fun?",
            "Wow! A superpowers drug you can just rub onto your skin? You'd think it would be something you'd have to freebase.",
            "Wow, you got that off the Internet? In my day, the Internet was only used to download pornography.",
        ],
        // "id" => 1
        "slug" => 1
    ],
    [
        "first-name" => "Turanga",
        "last-name" => "Leela",
        "image" => "https://upload.wikimedia.org/wikipedia/en/d/d4/Turanga_Leela.png",
        "age" => "32",
        "gender" => "Female",
        "species" => "Mutant",
        "homePlanet" => "Earth",
        "occupation" => "Captain and pilot",
        "sayings" => [
            "Bender, this is Fry's decision... and he made it wrong. So it's time for us to interfere in his life.",
            "With my Oxo Goodgrips cheese knife, I stab at thee!",
            "I usually try to keep my sadness pent up inside where it can fester quietly as a mental illness.",
            "I was having the most wonderful dream. Except you were there, and you were there, and you were there!",
            "That's not a career, more of a felony.",
            "That's not a warning! A warning's supposed come before something bad happens.",
            "This is my first visit to the Galaxy of Terror and I'd like it to be a pleasant one.",
            "This isn't heaven! It just looks exactly like it and makes us immortal! Which I find suspicious.",
            "Unit 10 - Target H, 16K - niner, niner! Go left - I mean right!",
            "What is the secret of time travel doing on Fry's ass?",
            "Do you have idiots on your planet?",
            "He opened up relations with China. He doesn't want to hear about your ding-dong.",
            "I'm a millionaire! Suddenly I have an opinion about the capital gains tax.",
            "My old life wasn't as glamorous as my webpage made it look.",
            "No, Leela will show you out.",
            "There's a political debate on. Quick, change the channel!",
            "This is by a wide margin the least likely thing that has ever happened.",
            "This toads the wet sprocket.",
            "This wangs chung.",
            "You did the best you could, I guess, and some of these gorillas are okay."
        ],
        "id" => 2
    ],
    [
        "first-name" => "Bender",
        "last-name" => "Rodriguez",
        "image" => "https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png",
        "age" => "25",
        "gender" => "Male",
        "species" => "Robot",
        "homePlanet" => "Earth",
        "occupation" => "Planet Express Worker",
        "sayings" => [
            "001100010010011110100001101101110011",
            "Ah, computer dating. It's like pimping, but you rarely have to use the phrase 'upside your head'.",
            "And the awkward meter goes up another notch. Ding-ding-ding-ding.",
            "Are all the tests gonna involve drinking?",
            "Behold, the internet.",
            "Bender knows love, and love doesn't share itself with the world. Love is suspicious, love is needy. Love is fearful, love is greedy. My friends, there is no great love without great jealousy! I love you meatbags!",
            "Bender must be stoped!  I've gone too far!  Who does that guy think I am!?",
            "Bite my shiny metal ass.",
            "Dumb-Dumb away!",
            "Emotions are dumb and should be hated.",
            "Finally, we made it out of that godforsaken cave! So what's the fastest way home, back through the cave?",
            "Fry! Quit doing the right thing, you jerk!",
            "Granted, it's not on the list of approved bendables, but I'm... so... great!",
            "Hasta la vista, Meatbag!",
            "Have you ever tried just turning off the TV, sitting down with your children, and hitting them?",
            "Hey, I don't tell you how to tell me what to do, so don't tell me how to do what you tell me to do!",
            "Hey that punk stole our hood ornament! Now no one will know we have the LX Package!",
            "Hey, what kinda party is this? There's no booze and only one hooker.",
            ],
        "id" => 3
    ],
    [
        "first-name" => "Hubert",
        "last-name" => "Farnsworth",
        "image" => "https://upload.wikimedia.org/wikipedia/en/0/0f/FuturamaProfessorFarnsworth.png",
        "age" => "210",
        "gender" => "Male",
        "species" => "Human",
        "homePlanet" => "Earth",
        "occupation" => "Scientist",
        "sayings" => [
            "Bender! Stop killing for a minute!",
            "Because your apartment smells like Polygrip and cat pee!",
            "Amy, technology isn't intrinsically good or evil. It's how it's used, like the death ray. ",
            "Just slow it down, I'll shoot Hitler out the window. Darn, I hit Eleanor Roosevelt by mistake!",
            "Just 'cause I'm stupider than them, they think they're smarter than me!",
            "Dear God, they'll be killed on our doorstep! And there's no trash pickup until January 3rd.",
            "Doomsday device? Ah, now the ball's in Farnsworth's court! I suppose I could part with one and still be feared…",
            "Everybody out of the conference room! I'm calling a conference!",
            "Goodbye, cruel world. Goodbye, cruel lamp. Goodbye, cruel velvet drapes, lined with what would appear to be some sort of cruel muslin and the cute little pom-pom curtain pull cords. Cruel though they may be...",
            "Good God! Just knowing we're in the same genus makes me embarrassed to call myself homo!",
            "Good news, everyone! I've taught the toaster to feel love!",
            "Good news, everyone! There's a report on TV with some very bad news!",
            "I am calling a mandatory company meeting. To the mandatorium!",
            "I can wire anything directly into anything - I'm the professor!",
        ],
        "id" => 4
    ],
];

return $data;
